#SIGN UP
GET http://localhost:2000/login
content-type: application/json
username: admin
password: salasana

###
#sendfile testing
GET http://localhost:2000/bigplaylist/00aashorttest.mp3

###
#token in URL test
GET http://localhost:2000/bigplaylist/00aashorttest.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYWRtaW4iLCJpYXQiOjE2MzQ4OTE0NTMsImV4cCI6MTYzNDk1MTQ1M30.ekQec4DO-2PorwT-yXBJYU_r3zj4ItL-Z59X3Udgryc

#vanhat alla väärällä portilla
###
#SHOW USERS
GET http://localhost:8080/auth/all

###
#LOGIN IP
GET https://13.48.136.183:443/login
content-type: application/json
username: admin
password: asdfasdf

###
#get songlist
GET http://13.48.136.183/getlist
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYWRtaW4iLCJpYXQiOjE2MzU5NDEyNDAsImV4cCI6MTYzNjU0MTI0MH0.RgTZpc_iO8EpoR0nw_DJaPSQejwus0A4WbSNYdWcBFQ

###
#LOGIN domain
GET http://myysic.xyz:2000/login
content-type: application/json
username: admin
password: sfsdsfd


###
#show
GET  http://13.48.136.183:2000/

###
#request with token
GET  http://localhost:8080/posts/private
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzQ3NDM2NDgsImV4cCI6MTYzNDgwMzY0OH0.D1YIaUXXjKIvxWRONG