#SIGN UP
GET http://localhost:2000/login
content-type: application/json
username: admin
password: salasana

###
#sendfile testing
GET http://localhost:2000/bigplaylist/00aashorttest.mp3

###
#token in URL test
GET http://localhost:2000/bigplaylist/00aashorttest.mp3?token=eyJhbGciiiiWRONG

#vanhat alla väärällä portilla
###
#SHOW USERS
GET http://localhost:8080/auth/all

###
#LOGIN IP
GET https://13.48.136.183:443/login
content-type: application/json
username: admin
password: asdfasdf

###
#get songlist
GET http://13.48.136.183/getlist
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5WRONG

###
#LOGIN domain
GET http://myysic.xyz:2000/login
content-type: application/json
username: admin
password: sfsdsfd


###
#show
GET  http://13.48.136.183:2000/

###
#request with token
GET  http://localhost:8080/posts/private
x-auth-token: eyJhbGiiiiiWRONG